/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2022-04-25 01:33:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.*;
import dao.*;
import util.*;
import java.util.ArrayList;
import java.io.*;

public final class productlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

// 선언문
	String title = "상품 목록";
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1650849076144L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1650849076153L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("util");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("dto");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//String uid = (String) session.getAttribute("id");
	//if (uid == null) {
	//	response.sendRedirect("/user/login.jsp");
	//	return;
	//} //세션 정보를 확인해서 로그인 상태인지 확인한후 진입 허용 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품 목록</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!-- CSS only -->\r\n");
      out.write("	<link\r\n");
      out.write("		href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("		rel=\"stylesheet\"\r\n");
      out.write("		integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("		crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("			<div id=\"header-wrapper\">\r\n");
      out.write("				<header id=\"header\" class=\"container\">\r\n");
      out.write("				  <!-- Logo -->\r\n");
      out.write("				  <div id=\"logo\">\r\n");
      out.write("               <img class=\"d-block mx-auto mb-4\" src=\"logo.png\" alt=\"\" width=\"150\" height=\"75\">\r\n");
      out.write("				  </div>\r\n");
      out.write("		\r\n");
      out.write("				  <!-- Nav -->\r\n");
      out.write("				  <nav id=\"nav\">\r\n");
      out.write("					<ul>\r\n");
      out.write("					  <li class=\"current\"><a href=\"index copy.html\">홈</a></li>\r\n");
      out.write("					  <li>\r\n");
      out.write("						<a href=\"index copy.html\">호텔 찾기</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("						  <li><a href=\"#\">지도별 검색</a></li>\r\n");
      out.write("						  <li><a href=\"#\">종별 검색</a></li>\r\n");
      out.write("						  <li><a href=\"#\">펫시터 찾기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					  </li>\r\n");
      out.write("					  <li><a href=\"left-sidebar.html\">펫시터 찾기</a></li>\r\n");
      out.write("					  <li><a href=\"right-sidebar.html\">반려동물 용품</a></li>\r\n");
      out.write("					  <li><a href=\"no-sidebar.html\">커뮤니티</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">보호자 커뮤니티</a></li>\r\n");
      out.write("							<li><a href=\"#\">보호자 대백과</a></li>\r\n");
      out.write("						  </li>\r\n");
      out.write("						  </ul>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\">위드펫과 함께하기</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">호텔 등록 신청</a></li>\r\n");
      out.write("								<li><a href=\"#\">펫시터 등록 신청</a>\r\n");
      out.write("							  </li>\r\n");
      out.write("							  </ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"#\">로그인</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("					  </ul>\r\n");
      out.write("					</ul>\r\n");
      out.write("				  </nav>\r\n");
      out.write("				</header>\r\n");
      out.write("			  </div>");
      out.write("\r\n");
      out.write("	<div class=\"alert alert-secondary\" role=\"alert\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h1 class=\"display-3\">\r\n");
      out.write("				");
      out.print(title);
      out.write("\r\n");
      out.write("			</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\" align=\"center\">\r\n");
      out.write("		\r\n");
      out.write("		");

			ArrayList<ProductDTO> products = (new ProductDAO()).getProductList();
			
		   for (ProductDTO product : products) {
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"col-md-4\">\r\n");
      out.write("				<img src=\"/withpet_mjs_ver02/images/");
      out.print(product.getImage() );
      out.write("\" style=\"width: 100%\">\r\n");
      out.write("					<h3>");
      out.print(product.getName() );
      out.write("</h3>\r\n");
      out.write("					<p>");
      out.print(product.getPrice() );
      out.write("원\r\n");
      out.write("					<p><a href=\"productdetail.jsp?pid=");
      out.print(product.getId() );
      out.write("\" class=\"btn btn-secondary\" role=\"button\">상세정보</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("			<!-- Footer -->\r\n");
      out.write("				<div id=\"footer-wrapper\">\r\n");
      out.write("					<footer id=\"footer\" class=\"container\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("								<!-- Links -->\r\n");
      out.write("									<section class=\"widget links\">\r\n");
      out.write("										<h3>Random Stuff</h3>\r\n");
      out.write("										<ul class=\"style2\">\r\n");
      out.write("											<li><a href=\"#\">Etiam feugiat condimentum</a></li>\r\n");
      out.write("											<li><a href=\"#\">Aliquam imperdiet suscipit odio</a></li>\r\n");
      out.write("											<li><a href=\"#\">Sed porttitor cras in erat nec</a></li>\r\n");
      out.write("											<li><a href=\"#\">Felis varius pellentesque potenti</a></li>\r\n");
      out.write("											<li><a href=\"#\">Nullam scelerisque blandit leo</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</section>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("								<!-- Links -->\r\n");
      out.write("									<section class=\"widget links\">\r\n");
      out.write("										<h3>Random Stuff</h3>\r\n");
      out.write("										<ul class=\"style2\">\r\n");
      out.write("											<li><a href=\"#\">Etiam feugiat condimentum</a></li>\r\n");
      out.write("											<li><a href=\"#\">Aliquam imperdiet suscipit odio</a></li>\r\n");
      out.write("											<li><a href=\"#\">Sed porttitor cras in erat nec</a></li>\r\n");
      out.write("											<li><a href=\"#\">Felis varius pellentesque potenti</a></li>\r\n");
      out.write("											<li><a href=\"#\">Nullam scelerisque blandit leo</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</section>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("								<!-- Links -->\r\n");
      out.write("									<section class=\"widget links\">\r\n");
      out.write("										<h3>Random Stuff</h3>\r\n");
      out.write("										<ul class=\"style2\">\r\n");
      out.write("											<li><a href=\"#\">Etiam feugiat condimentum</a></li>\r\n");
      out.write("											<li><a href=\"#\">Aliquam imperdiet suscipit odio</a></li>\r\n");
      out.write("											<li><a href=\"#\">Sed porttitor cras in erat nec</a></li>\r\n");
      out.write("											<li><a href=\"#\">Felis varius pellentesque potenti</a></li>\r\n");
      out.write("											<li><a href=\"#\">Nullam scelerisque blandit leo</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</section>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("								<!-- Contact -->\r\n");
      out.write("									<section class=\"widget contact last\">\r\n");
      out.write("										<h3>Contact Us</h3>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("											<li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("											<li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("											<li><a href=\"#\" class=\"icon brands fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("											<li><a href=\"#\" class=\"icon brands fa-pinterest\"><span class=\"label\">Pinterest</span></a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("										<p>1234 Fictional Road<br />\r\n");
      out.write("										Nashville, TN 00000<br />\r\n");
      out.write("										(800) 555-0000</p>\r\n");
      out.write("									</section>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<div id=\"copyright\">\r\n");
      out.write("									<ul class=\"menu\">\r\n");
      out.write("										<li>&copy; Untitled. All rights reserved</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</footer>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("\r\n");
      out.write("			<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript Bundle with Popper -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
