/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2022-04-25 01:21:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("   Verti by HTML5 UP\r\n");
      out.write("   html5up.net | @ajlkn\r\n");
      out.write("   Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>With Pet</title>\r\n");
      out.write("      <meta charset=\"utf-8\" />\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("   </head>\r\n");
      out.write("   <body class=\"is-preload homepage\">\r\n");
      out.write("      <div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("         <!-- Header -->\r\n");
      out.write("         <div id=\"header-wrapper\">\r\n");
      out.write("            <header id=\"header\" class=\"container\">\r\n");
      out.write("              <!-- Logo -->\r\n");
      out.write("              <div id=\"logo\">\r\n");
      out.write("               <img class=\"d-block mx-auto mb-4\" src=\"logo.png\" alt=\"\" width=\"150\" height=\"75\">\r\n");
      out.write("              </div>\r\n");
      out.write("      \r\n");
      out.write("              <!-- Nav -->\r\n");
      out.write("              <nav id=\"nav\">\r\n");
      out.write("               <ul>\r\n");
      out.write("                 <li class=\"current\"><a href=\"index copy.html\">홈</a></li>\r\n");
      out.write("                 <li>\r\n");
      out.write("                  <a href=\"index copy.html\">호텔 찾기</a>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li><a href=\"#\">지도별 검색</a></li>\r\n");
      out.write("                    <li><a href=\"#\">종별 검색</a></li>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                 </li>\r\n");
      out.write("                 <li><a href=\"petsitter/petsitter.html\">펫시터 찾기</a></li>\r\n");
      out.write("                 <li><a href=\"right-sidebar.html\">반려동물 용품</a></li>\r\n");
      out.write("                 <li><a href=\"no-sidebar.html\">커뮤니티</a>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                     <li><a href=\"#\">보호자 커뮤니티</a></li>\r\n");
      out.write("                     <li><a href=\"#\">보호자 대백과</a></li>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">위드펫과 함께하기</a>\r\n");
      out.write("                     <ul>\r\n");
      out.write("                        <li><a href=\"#\">호텔 등록 신청</a></li>\r\n");
      out.write("                        <li><a href=\"#\">펫시터 등록 신청</a>\r\n");
      out.write("                       </li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"user/login.jsp\">로그인</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"user/signin.jsp\">회원가입</a></li> \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("                 </ul>\r\n");
      out.write("               </ul>\r\n");
      out.write("              </nav>\r\n");
      out.write("            </header>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- Banner -->\r\n");
      out.write("            <div id=\"banner-wrapper\">\r\n");
      out.write("               <div id=\"banner\" class=\"box container\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-7 col-12-medium\">\r\n");
      out.write("                        <h2>위드펫</h2>\r\n");
      out.write("                        <h1>안녕하세요, 동물을 사랑하는 위드펫입니다. 안녕하세요, 동물을 사랑하는 위드펫입니다.안녕하세요, 동물을 사랑하는 위드펫입니다.안녕하세요, 동물을 사랑하는 위드펫입니다.안녕하세요, 동물을 사랑하는 위드펫입니다.안녕하세요, 동물을 사랑하는 위드펫입니다.안녕하세요, 동물을 사랑하는 위드펫입니다.</h1>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-13 col-20-medium\">\r\n");
      out.write("                        <img class=\"d-block mx-auto mb-4\" src=\"img/main4.png\" alt=\"\" width=\"400\" height=300\">\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- Features -->\r\n");
      out.write("            <div id=\"features-wrapper\">\r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-4 col-12-medium\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Box -->\r\n");
      out.write("                           <section class=\"box feature\">\r\n");
      out.write("                              <a href=\"#\" class=\"image featured\"><img src=\"img/hotel1.jpg\" alt=\"\" /></a>\r\n");
      out.write("                              <div class=\"inner\">\r\n");
      out.write("                                 <header>\r\n");
      out.write("                                    <h2>장기 숙박 EVENT</h2>\r\n");
      out.write("                                    <p>최대 3만원 할인</p>\r\n");
      out.write("                                 </header>\r\n");
      out.write("                                 <p>~4/30</p>\r\n");
      out.write("                                 <p>3박 이상 숙박시 쿠폰 지급</p>\r\n");
      out.write("                                 <button type=\"button\" class=\"btn btn-outline\" style=\"background-color: peachpuff;\">쿠폰 받으러 가기</button>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-4 col-12-medium\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Box -->\r\n");
      out.write("                           <section class=\"box feature\">\r\n");
      out.write("                              <a href=\"#\" class=\"image featured\"><img src=\"img/hotel2.jpg\" alt=\"\" /></a>\r\n");
      out.write("                              <div class=\"inner\">\r\n");
      out.write("                                 <header>\r\n");
      out.write("                                    <h2>첫 예약 EVENT</h2>\r\n");
      out.write("                                    <p>2만원 추가 할인</p>\r\n");
      out.write("                                 </header>\r\n");
      out.write("                                 <p>~행사 진행 중</p>\r\n");
      out.write("                                 <p>처음 예약하는 모든 고객에게 쿠폰 지급</p>\r\n");
      out.write("                                 <button type=\"button\" class=\"btn btn-outline\" style=\"background-color: peachpuff;\">쿠폰 받으러 가기</button>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-4 col-12-medium\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Box -->\r\n");
      out.write("                           <section class=\"box feature\">\r\n");
      out.write("                              <a href=\"#\" class=\"image featured\"><img src=\"img/snack.jpg\" alt=\"\" /></a>\r\n");
      out.write("                              <div class=\"inner\">\r\n");
      out.write("                                 <header>\r\n");
      out.write("                                    <h2>오늘의 특가 간식</h2>\r\n");
      out.write("                                    <p>유기농 간식 3종 특가 SALE</p>\r\n");
      out.write("                                 </header>\r\n");
      out.write("                                 <p>~5월 한 달간</p>\r\n");
      out.write("                                 <p>유기농 간식 3종세트 구매하는 고객에게 50% 할인</p>\r\n");
      out.write("                                 <button type=\"button\" class=\"btn btn-outline\" style=\"background-color: peachpuff\">구매하러 가기</button>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- Main -->\r\n");
      out.write("            <div id=\"main-wrapper\">\r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"row gtr-200\">\r\n");
      out.write("                     <div class=\"col-4 col-12-medium\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Sidebar -->\r\n");
      out.write("                           <div id=\"sidebar\">\r\n");
      out.write("                              <section class=\"widget thumbnails\">\r\n");
      out.write("                                 <h3>Interesting stuff</h3>\r\n");
      out.write("                                 <div class=\"grid\">\r\n");
      out.write("                                    <div class=\"row gtr-50\">\r\n");
      out.write("                                       <div class=\"col-6\"><a href=\"#\" class=\"image fit\"><img src=\"images/pic04.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("                                       <div class=\"col-6\"><a href=\"#\" class=\"image fit\"><img src=\"images/pic05.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("                                       <div class=\"col-6\"><a href=\"#\" class=\"image fit\"><img src=\"images/pic06.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("                                       <div class=\"col-6\"><a href=\"#\" class=\"image fit\"><img src=\"images/pic07.jpg\" alt=\"\" /></a></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <a href=\"#\" class=\"button icon fa-file-alt\">More</a>\r\n");
      out.write("                              </section>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-8 col-12-medium imp-medium\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Content -->\r\n");
      out.write("                           <div id=\"content\">\r\n");
      out.write("                              <section class=\"last\">\r\n");
      out.write("                                 <h2>So what's this all about?</h2>\r\n");
      out.write("                                 <p>This is <strong>Verti</strong>, a free and fully responsive HTML5 site template by <a href=\"http://html5up.net\">HTML5 UP</a>.\r\n");
      out.write("                                 Verti is released under the <a href=\"http://html5up.net/license\">Creative Commons Attribution license</a>, so feel free to use it for any personal or commercial project you might have going on (just don't forget to credit us for the design!)</p>\r\n");
      out.write("                                 <p>Phasellus quam turpis, feugiat sit amet ornare in, hendrerit in lectus. Praesent semper bibendum ipsum, et tristique augue fringilla eu. Vivamus id risus vel dolor auctor euismod quis eget mi. Etiam eu ante risus. Aliquam erat volutpat. Aliquam luctus mattis lectus sit amet phasellus quam turpis.</p>\r\n");
      out.write("                                 <a href=\"#\" class=\"button icon solid fa-arrow-circle-right\">Continue Reading</a>\r\n");
      out.write("                              </section>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- Footer -->\r\n");
      out.write("            <div id=\"footer-wrapper\">\r\n");
      out.write("               <footer id=\"footer\" class=\"container\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Links -->\r\n");
      out.write("                           <section class=\"widget links\">\r\n");
      out.write("                              <h3>개인정보 처리방침</h3>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Links -->\r\n");
      out.write("                           <section class=\"widget links\">\r\n");
      out.write("                              <h3>홈페이지 이용약관</h3>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Links -->\r\n");
      out.write("                           <section class=\"widget links\">\r\n");
      out.write("                              <h3>비회원 이용약관</h3>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-3 col-6-medium col-12-small\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Contact -->\r\n");
      out.write("                           <section class=\"widget contact last\">\r\n");
      out.write("                              <h3>Contact Us</h3>\r\n");
      out.write("                              <ul>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("                                 <li><a href=\"#\" class=\"icon brands fa-pinterest\"><span class=\"label\">Pinterest</span></a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                              <p>1234 Fictional Road<br />\r\n");
      out.write("                              Nashville, TN 00000<br />\r\n");
      out.write("                              (800) 555-0000</p>\r\n");
      out.write("                           </section>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-12\">\r\n");
      out.write("                        <div id=\"copyright\">\r\n");
      out.write("                           <ul class=\"menu\">\r\n");
      out.write("                              <li>&copy; Untitled. All rights reserved</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </footer>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Scripts -->\r\n");
      out.write("\r\n");
      out.write("         <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/util.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
